// Generated by https://quicktype.io  F1 -> Paste json as code

export interface News {
  news: NewsElement[];
}

export interface NewsElement {
  title:       string;
  description: string;
  category:    string;
  author:      string;
  date:        Date;
}
